

CREATE TABLE CANDIDATOS (
                          NOME VARCHAR2(200),
                          NUMERO INTEGER,
                          QTD_VOTOS INTEGER
);


INSERT INTO CANDIDATOS VALUES ('BOLSONARO',22,0);
INSERT INTO CANDIDATOS VALUES ('LULA',13,0);

SELECT * FROM CANDIDATOS;

TRUNCATE TABLE CANDIDATOS;


CREATE TABLE ELEITOR (
                       NOME VARCHAR2(200),
                       NOME_CAN VARCHAR2(200),
                       NUMERO_CAN INTEGER
);

SELECT * FROM ELEITOR;

TRUNCATE TABLE ELEITOR;


CREATE OR REPLACE PROCEDURE SP_VOTO_CANDIDATOS
(P_NOME_ELEITOR IN ELEITOR.NOME %TYPE,
 P_NUMERO IN CANDIDATOS.NUMERO %TYPE)
 IS
 V_QTD_VOTOS VARCHAR2(200);
 V_QTD INTEGER;
 BEGIN
INSERT INTO ELEITOR VALUES (P_NOME_ELEITOR,'',P_NUMERO);
COMMIT;

V_QTD_VOTOS := 'SELECT QTD_VOTOS FROM CANDIDATOS WHERE NUMERO = :P_NUMERO';
EXECUTE IMMEDIATE V_QTD_VOTOS INTO V_QTD USING P_NUMERO;

IF P_NUMERO = 13 THEN
   UPDATE CANDIDATOS
      SET QTD_VOTOS = V_QTD + 1
    WHERE NUMERO = P_NUMERO;
DBMS_OUTPUT.PUT_LINE(' VOCE VOTOU NO CANDIDATO'||' '||P_NUMERO);
COMMIT;

ELSIF P_NUMERO = 22 THEN 
 UPDATE CANDIDATOS
      SET QTD_VOTOS = V_QTD + 1
    WHERE NUMERO = P_NUMERO;
DBMS_OUTPUT.PUT_LINE(' VOCE VOTOU NO CANDIDATO'||' '||P_NUMERO);
COMMIT;

ELSE 
DBMS_OUTPUT.PUT_LINE('VOCE VOTOU EM BRANCO');

END IF;
END;



BEGIN 
  SP_VOTO_CANDIDATOS (P_NOME_ELEITOR => '&DIGITE_SEU_NOME',
                     P_NUMERO => &DIGITE_NUMERO_DO_CANDIDATO);
END;




CREATE OR REPLACE PROCEDURE SP_VOTO_CANDIDATOS_FRA
(P_NOME_ELEITOR IN ELEITOR.NOME %TYPE,
 P_NUMERO IN CANDIDATOS.NUMERO %TYPE)
 IS
 V_QTD_VOTOS VARCHAR2(200);
 V_QTD INTEGER;
 BEGIN
INSERT INTO ELEITOR VALUES (P_NOME_ELEITOR,'',P_NUMERO);
COMMIT;

V_QTD_VOTOS := 'SELECT QTD_VOTOS FROM CANDIDATOS WHERE NUMERO = :P_NUMERO';
EXECUTE IMMEDIATE V_QTD_VOTOS INTO V_QTD USING P_NUMERO;

IF P_NUMERO = 13 THEN
   UPDATE CANDIDATOS
      SET QTD_VOTOS = V_QTD + 1
    WHERE NUMERO = P_NUMERO;
DBMS_OUTPUT.PUT_LINE(' VOCE VOTOU NO CANDIDATO'||' '||P_NUMERO);
COMMIT;

ELSIF P_NUMERO = 22 THEN 
 UPDATE CANDIDATOS
      SET QTD_VOTOS = V_QTD + 1
    WHERE NUMERO = 13;
DBMS_OUTPUT.PUT_LINE(' VOCE VOTOU NO CANDIDATO'||' '||P_NUMERO);
COMMIT;

ELSE 
DBMS_OUTPUT.PUT_LINE('VOCE VOTOU EM BRANCO');

END IF;
END;


BEGIN 
  SP_VOTO_CANDIDATOS_FRA (P_NOME_ELEITOR => '&DIGITE_SEU_NOME',
                          P_NUMERO => &DIGITE_NUMERO_DO_CANDIDATO);
END;