
/*PARA ELIMINAR O PROJETO DO BANCO DE DADOS */



ALTER TABLE VENDAS
DROP CONSTRAINT FG_RELVAU_P_VAU;

ALTER TABLE VENDAS
DROP CONSTRAINT FG_RELVAU_P_CLI;

ALTER TABLE VENDAS
DROP CONSTRAINT FG_RELVAU_P_LOJ;



DROP TABLE CAD_CLI_02 PURGE;
DROP TABLE LOJISTA    PURGE;
DROP TABLE PRODUTO    PURGE;
DROP TABLE VAUCHER    PURGE;
DROP TABLE VENDAS     PURGE;




DROP SEQUENCE SEQ_CLI;
DROP SEQUENCE SEQ_PRO;
DROP SEQUENCE SEQ_LOJI;


DROP PROCEDURE SP_COD_PRO;
DROP PROCEDURE SP_LOJISTA;
DROP PACKAGE PKG_VOUCHER_DESC;
DROP PROCEDURE SP_CAD_CL;
DROP PROCEDURE SP_VENDAS;