
/*TABELAS DO BANCO DE DADOS*/




SET SERVEROUTPUT ON;




SELECT * FROM CAD_CLI_02;
SELECT * FROM LOJISTA;
SELECT * FROM PRODUTO;
SELECT * FROM VAUCHER;
SELECT * FROM VENDAS;






/*TABELA 01*/
CREATE TABLE CAD_CLI_02 (COD_CLI INTEGER CONSTRAINT PK_COD_CLI PRIMARY KEY
                            USING INDEX 
                              (CREATE INDEX IDX_CAD_COD 
                                  ON CAD_CLI_02(COD_CLI)),
                         CPF_CLI INTEGER NOT NULL,
                         NOME_CLI VARCHAR2(500));
                         
                         

ALTER TABLE CAD_CLI_02 
MODIFY CPF_CLI INTEGER UNIQUE;





/*TABELA 02*/
CREATE TABLE PRODUTO (COD_PRO INTEGER CONSTRAINT PK_COD_PRO PRIMARY KEY 
                          USING INDEX 
                            (CREATE INDEX IDX_PRO_COD 
                                 ON PRODUTO (COD_PRO)),
                      NOME_PRODUTO VARCHAR2(300),
                      PRECO_PRO NUMBER);
                      
                      
                      
/*TABELA 03*/                     
CREATE TABLE LOJISTA (COD_LOJ INTEGER CONSTRAINT PK_COD_LOJI PRIMARY KEY,
                      NOME_LOJISTA VARCHAR2(200));
                      



                    


/*TABELA 04*/
CREATE TABLE VAUCHER(COD_VAU VARCHAR2(200) CONSTRAINT PK_COD_VAU PRIMARY KEY,
                     PORCENTAGEM_DES NUMBER(8,2));





/*TABELA 05*/
CREATE TABLE VENDAS (COD_LOJ   INTEGER,
                     COD_CLI   INTEGER,
                     COD_PRO   INTEGER,
                TOTAL_COMPRA   NUMBER(8,2),
                     COD_VAU   VARCHAR2(100));
                     
                     
                               
ALTER TABLE VENDAS
RENAME COLUMN TOTAL_COM TO TOTAL_COMPRA;


ALTER TABLE VENDAS
ADD CONSTRAINT FG_RELVAU_P_VAU FOREIGN KEY (COD_VAU)
REFERENCES VAUCHER (COD_VAU);


ALTER TABLE VENDAS
ADD CONSTRAINT FG_RELVAU_P_CLI FOREIGN KEY (COD_CLI)
REFERENCES CAD_CLI_02 (CPF_CLI);


ALTER TABLE VENDAS
ADD CONSTRAINT FG_RELVAU_P_LOJ FOREIGN KEY (COD_LOJ)
REFERENCES LOJISTA (COD_LOJ);




/*VAUCHER CODIGOS PARA INSERIR NO PARAMETRO DA PROCEDURE
   NHZ3456KFSD 10%
   FHJ9078TGSL 20%
   QWH7856PMNG 30%
   JKB4539FFEW 40%
   LDR7856QPZF 50%
   
INSERT INTO VAUCHER VALUES('NHZ3456KFSD',0.1);
INSERT INTO VAUCHER VALUES('FHJ9078TGSL',0.2);
INSERT INTO VAUCHER VALUES('QWH7856PMNG',0.3);
INSERT INTO VAUCHER VALUES('JKB4539FFEW',0.4);
INSERT INTO VAUCHER VALUES('LDR7856QPZF',0.5);

*/
 

 /*ALTER TABLE CAD_CLI_02 
 DROP COLUMN TOTAL_COMPRA;*/


/*ALTER TABLE RELATORIO_VAUCHER
RENAME TO VENDAS;*/


